import MagicsClass

fireball = MagicsClass.AttackMagic("Fireball", 1.1, "Single", "Fire")
fireblast = MagicsClass.AttackMagic("Fireblast", 1.25, "Single", "Fire")
explosion = MagicsClass.AttackMagic("Explosion", 1.75, "All", "Fire")
iceshard = MagicsClass.AttackMagic("Ice Shard", 1.0, "Single", "Ice")
frost = MagicsClass.AttackMagic("Frost", 1.25, "Single", "Ice")
blizzard = MagicsClass.AttackMagic("Blizzard", 1.75, "All", "Ice")
thunder = MagicsClass.AttackMagic("Thunder", 1.0, "Single", "Lightning")
thunderbolt = MagicsClass.AttackMagic("Thunder Bolt", 1.25, "Single", "Lightning")
thunderstorm = MagicsClass.AttackMagic("Thunder Storm", 1.75, "All", "Lightning")
quake = MagicsClass.AttackMagic("Quake", 1.0, "All", "Earth")
earthquake = MagicsClass.AttackMagic("Earthquake", 1.35, "All", "Earth")
wind = MagicsClass.AttackMagic("Wind", 1.2, "Single", "Wind")
tornado = MagicsClass.AttackMagic("Tornado", 1.45, "All", "Wind")
holy = MagicsClass.AttackMagic("Holy", 2.0, "Single", "Light")
dark = MagicsClass.AttackMagic("Dark", 2.0, "Single", "Dark")
comet = MagicsClass.AttackMagic("Comet", 1.75, "Single", "Non-Elemental")
meteor = MagicsClass.AttackMagic("Meteor", 2.5, "All", "Non-Elemental")
ultima = MagicsClass.AttackMagic("Ultima", 3.0, "All", "Non-Elemental")